# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: joystick.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='joystick.proto',
  package='gazebo.msgs',
  serialized_pb=_b('\n\x0ejoystick.proto\x12\x0bgazebo.msgs\")\n\x08Joystick\x12\x0c\n\x04\x61xes\x18\x01 \x03(\x01\x12\x0f\n\x07\x62uttons\x18\x02 \x03(\x08\x42\x0c\x42\nGzJoystick')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_JOYSTICK = _descriptor.Descriptor(
  name='Joystick',
  full_name='gazebo.msgs.Joystick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axes', full_name='gazebo.msgs.Joystick.axes', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buttons', full_name='gazebo.msgs.Joystick.buttons', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['Joystick'] = _JOYSTICK

Joystick = _reflection.GeneratedProtocolMessageType('Joystick', (_message.Message,), dict(
  DESCRIPTOR = _JOYSTICK,
  __module__ = 'joystick_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Joystick)
  ))
_sym_db.RegisterMessage(Joystick)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\nGzJoystick'))
# @@protoc_insertion_point(module_scope)
