from . import _init_shuffleboard

# TODO: shuffleboard broken in wpilibc beta 1
# # autogenerated by 'robotpy-build create-imports wpilib.shuffleboard'
# from ._shuffleboard import (
#     BuiltInLayouts,
#     BuiltInWidgets,
#     ComplexWidget,
#     LayoutType,
#     Shuffleboard,
#     ShuffleboardComponentBase,
#     ShuffleboardContainer,
#     ShuffleboardEventImportance,
#     ShuffleboardLayout,
#     ShuffleboardTab,
#     ShuffleboardValue,
#     SimpleWidget,
#     SuppliedBoolValueWidget,
#     SuppliedDoubleListValueWidget,
#     SuppliedDoubleValueWidget,
#     SuppliedIntListValueWidget,
#     SuppliedRawListValueWidget,
#     SuppliedRawValueWidget,
#     SuppliedStringListValueWidget,
#     SuppliedStringValueWidget,
#     WidgetType,
#     shuffleboardEventImportanceName,
# )

# __all__ = [
#     "BuiltInLayouts",
#     "BuiltInWidgets",
#     "ComplexWidget",
#     "LayoutType",
#     "Shuffleboard",
#     "ShuffleboardComponentBase",
#     "ShuffleboardContainer",
#     "ShuffleboardEventImportance",
#     "ShuffleboardLayout",
#     "ShuffleboardTab",
#     "ShuffleboardValue",
#     "SimpleWidget",
#     "SuppliedBoolValueWidget",
#     "SuppliedDoubleListValueWidget",
#     "SuppliedDoubleValueWidget",
#     "SuppliedIntListValueWidget",
#     "SuppliedRawListValueWidget",
#     "SuppliedRawValueWidget",
#     "SuppliedStringListValueWidget",
#     "SuppliedStringValueWidget",
#     "WidgetType",
#     "shuffleboardEventImportanceName",
# ]

del _init_shuffleboard
